name: Build OpenWrt Docker image

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"

env:
  FIRMWARE_URL_ARM64: "https://github.com/mj22226/openwrt/releases/download/bcm2712-6.1/openwrt-bcm27xx-bcm2712-rpi-5-ext4-factory-arm64.img.gz"
  REPOSITORY: li79430/jonney
  TAG: 24.0.10

jobs:
  build:
    name: "Build OpenWrt docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Firmware
        run: |
          wget $FIRMWARE_URL -O openwrt.tar.gz

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          FIRMWARE: openwrt.tar.gz
        with:
          name: ${{ env.REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: FIRMWARE
          tags: "latest,${{ env.TAG }}"
