name: Build OpenWrt Docker x86-64 image

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"

env:
  FIRMWARE_URL: "https://public.bl.files.1drv.com/y4m2GyRvlRlLcyf051Z9UABYY4gdFG6jWNdOC4C9m2CBU5_S0gD02N_gaibmerrVqAoQdhd_L7feiTLKwttdX49Dt_03qWTxZnUz0SMHD9VnF27px-esT3LsPbOGWGZHYN8u0nx1_o0bTSvKzA1VGZ1WoeTLpS9IVLESdL4PpWcM56UkhYQ-cTVXp6dk5RH7-uyV46ZFQ7zgXAvd1sqP4Bo76BrTDSACBWkBbboxlbZisY?AVOverride=1"
  REPOSITORY: lhy0315cn/onecloud
  TAG: 23.08.26

jobs:
  build:
    name: "Build OpenWrt docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Firmware
        run: |
          wget $FIRMWARE_URL -O openwrt.tar.gz

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          FIRMWARE: openwrt.tar.gz
        with:
          name: ${{ env.REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: FIRMWARE
          tags: "latest,${{ env.TAG }}"
