name: Build OpenWrt Docker image

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"

env:
  FIRMWARE_URL: "https://github.com/mj22226/openwrt/releases/download/rpi-6.6-4045fb89fd1b3d5abeb07c4b06176574c4dd9f0e/openwrt-bcm27xx-bcm2712-rpi-5-ext4-factory.img.gz"
  REPOSITORY: li79430/jonney
  TAG: 24.0.12

jobs:
  build:
    name: "Build OpenWrt docker image"
    runs-on: debian:stable-20240211-slim
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Firmware
        run: |
          wget $FIRMWARE_URL -O openwrt.tar.gz

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          FIRMWARE: openwrt.tar.gz
        with:
          name: ${{ env.REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: FIRMWARE
          tags: "latest,${{ env.TAG }}"
